name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
    packages: write
    attestations: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
              
    - name: Build the Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 --tag ghcr.io/eliotstocker/alpine-tunnel-container:latest --push .
